application: alarm
version: 1
runtime: python
api_version: 1

handlers:
- url: /sitemedia/css
  static_dir: media/css

- url: /sitemedia/js
  static_dir: media/js

- url: /sitemedia/img
  static_dir: media/img
  
- url: /sitemedia/fonts
  static_dir: media/fonts

- url: /sitemedia/songs
  static_dir: media/songs

- url: /.*
  script: alarm.py
